# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
